version: '3'
services:
  vppsim:
    image: vppsim
    build:
      context: .
    ports:
      - 8080:8080
    volumes:
      - "./config.json:/etc/vppsim/config.json:ro"
    command: ["start", "/etc/vppsim/config.json"]