language: node_js
node_js:
  - "7"
python:
  - "3.6"
cache:
  yarn: true
  directories:
    - "ui/node_modules"
env:
  - NODE_ENV=production
install:
  - cd ui && yarn --production=false
script:
  - ./node_modules/.bin/webpack
