version: "3"
services:
  commandment:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: commandment:latest
    volumes:
      - "./settings.cfg:/settings.cfg"
    ports:
      - "8120:80"