version: "3"
services:
  commandment:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: commandment:latest
    volumes:
      - "./.docker/settings.cfg.docker:/settings.cfg"
      - "./ssl.crt:/etc/nginx/ssl.crt"
      - "./ssl.key:/etc/nginx/ssl.key"
    ports:
      - "8445:443"