version: '3'
services:
  depsim:
    image: depsim
    build:
      context: .
    ports:
      - 8080:8080
    volumes:
      - "./config.json:/etc/depsim/config.json:ro"
    command: ["start", "/etc/depsim/config.json"]